version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  apicrawl:
    container_name: apicrawl
    build:
      context: ./services/apicrawl
      dockerfile: Dockerfile
    volumes:
      - './services/apicrawl/src:/usr/src/app/src'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
